### ISSUE TITLE
crash when updated to latest version

### ISSUE THREAD

**Issue by charliez0** [Builderdog841/Ancient-Aether#171]
the game can start but joining any world would lead to rendering crash

**Comment by Builderdog841** [comment]
do you have Aether Redux installed? Since Redux currently has an issue that causes Ancient Aether to crash, otherwise provide a crashlog

**Comment by charliez0** [comment]
> do you have Aether Redux installed? Since Redux currently has an issue that causes Ancient Aether to crash, otherwise provide a crashlog

yes, but installed v0.8.5 of ancient aether won't crash👀

**Comment by Builderdog841** [comment]
then please provide a crashlog so I actually can look into this issue

**Comment by charliez0** [comment]
https://mclo.gs/UHCU1mX

**Comment by Builderdog841** [comment]
You do not have Ancient Aether v0.8.5 installed, you have the latest version installed. Though I'd honestly not recommend using any Ancient Aether Version with Redux atm since currently the Aether Redux mod is has excessive amount of bugs and there are a lot more when playing with Ancient Aether and Redux. Redux is currently going through a major rework of all its content and implementation, this update also includes proper Ancient Aether compatibility so I do not recommend using both mods before this version releases.
